name: Playbook CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_server_image:
    name: "Build Docker image for server and client"
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker server image
      - uses: actions/checkout@v3
        run: |
          cd server
          time=$(date +%s)
          docker build . --file Dockerfile --tag elhambadri2411/playbook-amey-elham-server:$time
          docker push elhambadri2411/playbook-amey-elham-server:$time

      - name: Build the Docker client image
      - uses: actions/checkout@v3
        run: |
          cd client
          time=$(date +%s)
          docker build . --file Dockerfile --tag elhambadri2411/playbook-amey-elham-client:$time
          docker push elhambadri2411/playbook-amey-elham-client:$time
