name: Playbook CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_playbook_image:
    name: "Build Docker image for server and client"
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build the Docker server image
        run: |
          cd server
          time=$(date +%s)
          docker build . --file Dockerfile --tag elhambadri2411/playbook-amey-elham-server:$time
          docker push elhambadri2411/playbook-amey-elham-server:$time

      - name: Build the Docker client image
        run: |
          cd client
          time=$(date +%s)
          docker build . --file Dockerfile --tag elhambadri2411/playbook-amey-elham-client:$time
          docker push elhambadri2411/playbook-amey-elham-client:$time
